repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # frozen: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/tombi-toml/tombi-pre-commit
    rev: 84223797550a899b3a0d89179934e5f91b8ee4d1  # frozen: v1.5.1
    hooks:
      - id: tombi-format
        args: ["--offline"]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 321478e58f4938179c6b86e4ddfa923d1547a49b  # frozen: v0.16.6
    hooks:
      - id: ruff-check
        args: [--fix]
        types_or: [python, pyi]
      - id: ruff-format
        types_or: [python, pyi, markdown]
