# pyright: reportPrivateUsage=false
"""Hardware-independent quantum authoring facade."""

from scopecat_quantum.acquisitions import (
    CLASSIFIED_STATE_RESULT,
    INTEGRATED_IQ_RESULT,
    AcquisitionKind,
    QuantumResultContract,
    QuantumResultDimension,
    raw_trace_result,
)

from ._analysis import (
    program_port_type,
)
from ._binding import (
    BoundProgram,
    bind,
)
from ._binding import (
    materialize_pulse_recipe_body as materialize_pulse_recipe_body,
)
from ._construction import (
    _close_program as _close_program,
)
from ._construction import (
    acquire,
    constant,
    cosine_flat_top,
    coupler,
    delay,
    derivative_quadrature,
    drag,
    drive,
    flux,
    fragment,
    frequency_shift,
    gate,
    gaussian,
    implementation,
    input,
    measure,
    parallel,
    parallel_each,
    play,
    program,
    pulse_template,
    qubit,
    readout,
    repeat,
    scalar_input,
    sequence,
    shift_phase,
    single_qubit_gate,
    switch,
    two_qubit_gate,
)
from ._definitions import (
    FragmentDefinition,
    Gate,
    GateImplementationDefinition,
    ProgramFamilyEnvelope,
    PulseTemplateDefinition,
    SingleQubitGate,
    TwoQubitGate,
)
from ._definitions import (
    _implement_gate as _implement_gate,
)
from ._expressions import QuantityExpression
from ._inspection import (
    describe,
    draw,
)
from ._ir import (
    QUANTUM_PROGRAM_DIALECT_ID,
    QUANTUM_PROGRAM_DIALECT_VERSION,
    Acquisition,
    CircuitArgument,
    CircuitFragment,
    Coupler,
    CouplerInput,
    CouplerSet,
    EntitySetPort,
    Measurement,
    MeasurementResult,
    ProgramBindingError,
    ProgramInput,
    ProgramPort,
    ProgramResult,
    ProgramResults,
    PulseElement,
    PulseEnvelope,
    PulseFragment,
    QuantumFragment,
    QuantumQuantity,
    Qubit,
    QubitInput,
    QubitPair,
    QubitPairSet,
    QubitSet,
    RepeatCount,
)
from ._programs import (
    Program,
    ProgramDefinition,
    QuantumProgramCall,
)
from ._selection import (
    CouplerSelectionIntent,
    QubitPairSelectionIntent,
    QubitSelectionIntent,
    select_couplers,
    select_qubit_pairs,
    select_qubits,
)

__all__ = [
    "CLASSIFIED_STATE_RESULT",
    "INTEGRATED_IQ_RESULT",
    "QUANTUM_PROGRAM_DIALECT_ID",
    "QUANTUM_PROGRAM_DIALECT_VERSION",
    "Acquisition",
    "AcquisitionKind",
    "BoundProgram",
    "CircuitArgument",
    "CircuitFragment",
    "Coupler",
    "CouplerInput",
    "CouplerSelectionIntent",
    "CouplerSet",
    "EntitySetPort",
    "FragmentDefinition",
    "Gate",
    "GateImplementationDefinition",
    "Measurement",
    "MeasurementResult",
    "Program",
    "ProgramBindingError",
    "ProgramDefinition",
    "ProgramFamilyEnvelope",
    "ProgramInput",
    "ProgramPort",
    "ProgramResult",
    "ProgramResults",
    "PulseElement",
    "PulseEnvelope",
    "PulseFragment",
    "PulseTemplateDefinition",
    "QuantityExpression",
    "QuantumFragment",
    "QuantumProgramCall",
    "QuantumQuantity",
    "QuantumResultContract",
    "QuantumResultDimension",
    "Qubit",
    "QubitInput",
    "QubitPair",
    "QubitPairSelectionIntent",
    "QubitPairSet",
    "QubitSelectionIntent",
    "QubitSet",
    "RepeatCount",
    "SingleQubitGate",
    "TwoQubitGate",
    "acquire",
    "bind",
    "constant",
    "cosine_flat_top",
    "coupler",
    "delay",
    "derivative_quadrature",
    "describe",
    "drag",
    "draw",
    "drive",
    "flux",
    "fragment",
    "frequency_shift",
    "gate",
    "gaussian",
    "implementation",
    "input",
    "measure",
    "parallel",
    "parallel_each",
    "play",
    "program",
    "program_port_type",
    "pulse_template",
    "qubit",
    "raw_trace_result",
    "readout",
    "repeat",
    "scalar_input",
    "select_couplers",
    "select_qubit_pairs",
    "select_qubits",
    "sequence",
    "shift_phase",
    "single_qubit_gate",
    "switch",
    "two_qubit_gate",
]
