// @vitest-environment jsdom

import "@testing-library/jest-dom/vitest";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { cleanup, fireEvent, render, screen } from "@testing-library/react";
import { afterEach, describe, expect, it, vi } from "vitest";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { LaunchWorkspace } from "../features/launch/LaunchWorkspace";
import type { components } from "../api-schema";
import { getRunParameterProposals } from "../data/parameter-proposals/api";
import { getReview } from "../features/reviews/review-api";
import { getMeasurementPreview } from "../features/runs/run-api";
import { MeasurementDataPreview } from "../features/runs/MeasurementDataPreview";
import { measurementEntityAxes } from "../features/runs/measurement-visualization";

// Generated by real Python/HTTP workflows; no separately authored response mocks.
const fixtures = JSON.parse(
  readFileSync(
    resolve(process.cwd(), "../../examples/reference_lab/fixtures/acceptance.json"),
    "utf8",
  ),
) as {
  launch_catalog: components["schemas"]["LaunchCatalog"];
  launch_preview: components["schemas"]["LaunchPreview"];
  diagnostic: components["schemas"]["MeasurementPreview"];
  inspection: components["schemas"]["ReviewSessionView"];
  reviewed_candidate: components["schemas"]["ParameterProposalPage"];
  entity_analysis: components["schemas"]["MeasurementDatasetSchema-Output"];
};

vi.mock("../ui/EChartRuntime", () => ({ EChartRuntime: () => null }));
afterEach(() => {
  cleanup();
  vi.unstubAllGlobals();
});

function serve(value: unknown) {
  vi.stubGlobal(
    "fetch",
    vi.fn(() =>
      Promise.resolve(
        new Response(JSON.stringify(value), { headers: { "Content-Type": "application/json" } }),
      ),
    ),
  );
}

describe("shared reference-lab acceptance", () => {
  it("uses the real diagnostic and reviewed-calibration catalog in the launcher", async () => {
    vi.stubGlobal(
      "fetch",
      vi.fn((request: Request) =>
        Promise.resolve(
          Response.json(
            new URL(request.url).pathname.endsWith("/preview")
              ? fixtures.launch_preview
              : fixtures.launch_catalog,
          ),
        ),
      ),
    );
    render(
      <QueryClientProvider
        client={new QueryClient({ defaultOptions: { queries: { retry: false } } })}
      >
        <LaunchWorkspace />
      </QueryClientProvider>,
    );
    await screen.findByRole("option", { name: "Q1 channel timing candidate" });
    fireEvent.click(screen.getByRole("button", { name: "Preview" }));
    await screen.findByText("Preview ready");
    expect(
      screen.getByText("This procedure does not change the default configuration."),
    ).toBeVisible();
    expect(screen.getByRole("button", { name: "Start acquisition" })).toBeEnabled();
  });

  it("renders the retained read-only thermometer sample through the real API adapter", async () => {
    serve(fixtures.diagnostic);
    const preview = await getMeasurementPreview("acceptance-diagnostic");
    render(
      <MeasurementDataPreview
        preview={preview}
        sliceError={null}
        slicePending={false}
        fixedAxisIndices={{}}
        onFixedAxisIndexChange={() => {}}
      />,
    );
    expect(screen.getByText("0.02 K")).toBeVisible();
    expect(preview.items[0]?.acquisition_evidence?.events?.[0]?.instrument_id).toBe(
      "mixing-chamber",
    );
  });

  it("reads the reviewed candidate without discarding its approval or table delta", async () => {
    serve(fixtures.reviewed_candidate);
    const page = await getRunParameterProposals("acceptance-source");
    expect(page.items).toHaveLength(1);
    expect(page.items[0]?.id).toBe("q1-channel-delay");
    expect(page.items[0]?.approval?.actor).toBe("acceptance-operator");
    expect(page.items[0]?.deltas[0]?.parameterId).toBe("channel_calibrations");
    expect(page.items[0]?.deltas[0]?.before).not.toEqual(page.items[0]?.deltas[0]?.after);
  });

  it("consumes the same read-only inspection and entity-indexed schema", async () => {
    serve(fixtures.inspection);
    const review = await getReview("acceptance-inspection");
    expect(review.experiment_id).toBe("reference_lab.temperature_diagnostic");
    expect(review.latest_result?.error).toBeNull();
    expect(
      measurementEntityAxes(fixtures.entity_analysis)[0]?.members.map((entity) => entity.id),
    ).toEqual(["q0", "q1"]);
  });
});
