// @vitest-environment jsdom

import "@testing-library/jest-dom/vitest";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { afterEach, describe, expect, it, vi } from "vitest";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { PlannedSettings } from "../features/launch/PlannedSettings";
import { LaunchDraftProvider } from "../features/launch/LaunchDraft";
import { LaunchWorkspace } from "../features/launch/LaunchWorkspace";
import type { components } from "../api-schema";
import { getRunParameterProposals } from "../data/parameter-proposals/api";
import { getReview } from "../features/reviews/review-api";
import { getMeasurementPreview } from "../features/runs/run-api";
import { MeasurementDataPreview } from "../features/runs/MeasurementDataPreview";
import {
  measurementEntityAxes,
  planMeasurementCharts,
} from "../features/runs/measurement-visualization";

// Generated by real Python/HTTP workflows; no separately authored response mocks.
const fixtures = JSON.parse(
  readFileSync(
    resolve(process.cwd(), "../../examples/reference_lab/fixtures/acceptance.json"),
    "utf8",
  ),
) as {
  planned_settings: Pick<
    components["schemas"]["PreflightStage"],
    "planned_settings" | "planned_setting_limit" | "planned_settings_truncated" | "selected_points"
  >;
  launch_catalog: components["schemas"]["LaunchCatalog"];
  launch_preview: components["schemas"]["LaunchPreview"];
  diagnostic: components["schemas"]["MeasurementPreview"];
  controls_scalar: components["schemas"]["LaunchPreview"];
  controls_scan: components["schemas"]["LaunchPreview"];
  coherent_scalar: components["schemas"]["MeasurementPreview"];
  inspection: components["schemas"]["ReviewSessionView"];
  reviewed_candidate: components["schemas"]["ParameterProposalPage"];
  entity_analysis: components["schemas"]["MeasurementDatasetSchema-Output"];
};

vi.mock("../ui/EChartRuntime", () => ({ EChartRuntime: () => null }));
afterEach(() => {
  cleanup();
  vi.unstubAllGlobals();
});

function serve(value: unknown) {
  vi.stubGlobal(
    "fetch",
    vi.fn(() =>
      Promise.resolve(
        new Response(JSON.stringify(value), { headers: { "Content-Type": "application/json" } }),
      ),
    ),
  );
}

describe("shared reference-lab acceptance", () => {
  it("renders the reference planned source frequency without device observation", () => {
    render(<PlannedSettings stage={fixtures.planned_settings} />);
    expect(screen.getByText("4850000000 Hz")).toBeVisible();
    expect(screen.getByText(/drive-lo-a.*frequency/)).toBeVisible();
    expect(screen.getByText(/not observed or confirmed state/)).toBeVisible();
  });
  it("uses the real diagnostic and reviewed-calibration catalog in the launcher", async () => {
    vi.stubGlobal(
      "fetch",
      vi.fn((request: Request) =>
        Promise.resolve(
          Response.json(
            new URL(request.url).pathname.endsWith("/config-registry")
              ? {
                  activation: {
                    entry_id: fixtures.launch_preview.config_source?.entry_id,
                    generation: fixtures.launch_preview.config_source?.registry_generation,
                  },
                  entries: [],
                }
              : new URL(request.url).pathname.endsWith("/preview")
                ? fixtures.launch_preview
                : fixtures.launch_catalog,
          ),
        ),
      ),
    );
    render(
      <QueryClientProvider
        client={new QueryClient({ defaultOptions: { queries: { retry: false } } })}
      >
        <LaunchDraftProvider projectId="reference-lab">
          <LaunchWorkspace />
        </LaunchDraftProvider>
      </QueryClientProvider>,
    );
    await screen.findByRole("option", { name: "Q1 channel timing candidate" });
    fireEvent.click(screen.getByRole("button", { name: "Preview" }));
    await screen.findByText("Preview ready");
    expect(
      screen.getByText("This procedure does not change the default configuration."),
    ).toBeVisible();
    expect(screen.getAllByText("Retained (planned dataset)")).toHaveLength(2);
    expect(screen.getByText("Unknown (s)")).toBeVisible();
    expect(screen.getByText(/1\/64 displayed points; 1\/1 selected points/)).toBeVisible();
    expect(screen.getByRole("button", { name: "Start acquisition" })).toBeEnabled();
  });

  it("uses the shared controls catalog for fixed and scanned previews with owned provenance", async () => {
    const requests: Record<string, unknown>[] = [];
    let submitted: Record<string, unknown> | undefined;
    vi.stubGlobal(
      "fetch",
      vi.fn(async (request: Request) => {
        const path = new URL(request.url).pathname;
        if (path.endsWith("/config-registry"))
          return Response.json({
            activation: {
              entry_id: fixtures.controls_scan.config_source?.entry_id,
              generation: fixtures.controls_scan.config_source?.registry_generation,
            },
            entries: [],
          });
        if (path.endsWith("/submit")) {
          submitted = await request.json();
          throw new TypeError("Submission response lost");
        }
        if (path.endsWith("/preview")) {
          requests.push(await request.json());
          return Response.json(
            requests.length === 1 ? fixtures.controls_scalar : fixtures.controls_scan,
          );
        }
        if (path.endsWith("/procedures")) return Response.json({ items: [], next_cursor: null });
        return Response.json(fixtures.launch_catalog);
      }),
    );
    render(
      <QueryClientProvider
        client={new QueryClient({ defaultOptions: { queries: { retry: false } } })}
      >
        <LaunchDraftProvider projectId="reference-lab">
          <LaunchWorkspace />
        </LaunchDraftProvider>
      </QueryClientProvider>,
    );
    fireEvent.change(await screen.findByLabelText("Experiment"), {
      target: { value: "frequency-amplitude" },
    });
    expect(screen.getByText(/Configuration-owned/)).toHaveTextContent("qubits[q0]");
    fireEvent.change(screen.getByLabelText("Frequency unit"), { target: { value: "MHz" } });
    fireEvent.change(screen.getByLabelText("Frequency"), { target: { value: "4900" } });
    fireEvent.click(screen.getByRole("button", { name: "Preview" }));
    await screen.findByText("Resolved controls");
    expect(screen.getAllByText("fixed")).toHaveLength(2);
    expect(screen.getByText("configuration")).toBeVisible();
    expect(screen.getByText("derived")).toBeVisible();
    expect(requests[0]?.control_edits).toMatchObject({
      frequency: { mode: "fixed", value: { value: 4900, unit: "MHz" } },
    });
    fireEvent.change(screen.getByLabelText("Frequency source"), { target: { value: "range" } });
    expect(screen.queryByText("Resolved controls")).toBeNull();
    expect(screen.getByRole("button", { name: "Start acquisition" })).toBeDisabled();
    fireEvent.change(screen.getByLabelText("Frequency start"), { target: { value: "4.7" } });
    fireEvent.change(screen.getByLabelText("Frequency stop"), { target: { value: "4.9" } });
    fireEvent.change(screen.getByLabelText("Frequency points"), { target: { value: "3" } });
    fireEvent.change(screen.getByLabelText("Amplitude source"), { target: { value: "values" } });
    fireEvent.change(screen.getByLabelText("Amplitude scan values"), {
      target: { value: "0.05, 0.1" },
    });
    fireEvent.click(screen.getByRole("button", { name: "Preview" }));
    await screen.findByText("Resolved controls");
    expect(screen.getAllByText("scanned")).toHaveLength(2);
    const edits = requests[1]?.control_edits;
    expect(edits).toMatchObject({
      frequency: { mode: "scan", axis: { kind: "range", points: 3 } },
      amplitude: { mode: "scan", axis: { kind: "values" } },
    });
    expect(JSON.stringify(edits)).not.toContain("4900");
    await waitFor(() =>
      expect(screen.getByRole("button", { name: "Start acquisition" })).toBeEnabled(),
    );
    fireEvent.click(screen.getByRole("button", { name: "Start acquisition" }));
    await waitFor(() => expect(submitted).toBeDefined());
    expect(submitted?.control_edits).toEqual(edits);
    expect(submitted?.expected_request_hash).toEqual(fixtures.controls_scan.request_hash);
  });

  it("renders the retained read-only thermometer sample through the real API adapter", async () => {
    serve(fixtures.diagnostic);
    const preview = await getMeasurementPreview("acceptance-diagnostic");
    render(
      <MeasurementDataPreview
        preview={preview}
        sliceError={null}
        slicePending={false}
        fixedAxisIndices={{}}
        onFixedAxisIndexChange={() => {}}
      />,
    );
    expect(screen.getByText("0.02 K")).toBeVisible();
    expect(preview.items[0]?.acquisition_evidence?.events?.[0]?.instrument_id).toBe(
      "mixing-chamber",
    );
  });

  it("displays the stored coherent scalar grid in all four complex modes", async () => {
    serve(fixtures.coherent_scalar);
    const preview = await getMeasurementPreview("acceptance-coherent");
    const heatmaps = planMeasurementCharts(preview.items, preview.schema).filter(
      (chart) => chart.kind === "heatmap",
    );
    expect(heatmaps).toHaveLength(4);
    render(
      <MeasurementDataPreview
        preview={preview}
        slice={{
          items: preview.items,
          schema: preview.schema,
          selectedPointCount: preview.items.length,
          offset: 0,
          windowPointCount: preview.items.length,
          truncated: false,
        }}
        sliceError={null}
        slicePending={false}
        fixedAxisIndices={{}}
        onFixedAxisIndexChange={() => {}}
      />,
    );
    const selector = screen.getByRole("combobox", { name: "Measurement chart" });
    for (const chart of heatmaps) {
      fireEvent.change(selector, { target: { value: chart.id } });
      expect(screen.getByRole("img", { name: new RegExp(`^${chart.title}:`) })).toBeVisible();
    }
    expect(heatmaps.map((chart) => chart.title)).toEqual([
      "Iq Mean magnitude heatmap",
      "Iq Mean phase heatmap",
      "Iq Mean real heatmap",
      "Iq Mean imaginary heatmap",
    ]);
    const real = heatmaps[2]!.series[0]!.points[0]!.color!;
    const imag = heatmaps[3]!.series[0]!.points[0]!.color!;
    expect(imag).not.toBe(0);
    expect(heatmaps[0]!.series[0]!.points[0]!.color).toBeCloseTo(Math.hypot(real, imag));
    expect(heatmaps[1]!.series[0]!.points[0]!.color).toBeCloseTo(Math.atan2(imag, real));
    expect(heatmaps.map((chart) => chart.colorLabel)).toEqual([
      "|Iq Mean| [ratio]",
      "phase(Iq Mean) [rad]",
      "Re(Iq Mean) [ratio]",
      "Im(Iq Mean) [ratio]",
    ]);
  });

  it("reads the reviewed candidate without discarding its approval or table delta", async () => {
    serve(fixtures.reviewed_candidate);
    const page = await getRunParameterProposals("acceptance-source");
    expect(page.items).toHaveLength(1);
    expect(page.items[0]?.id).toBe("q1-channel-delay");
    expect(page.items[0]?.approval?.actor).toBe("acceptance-operator");
    expect(page.items[0]?.deltas[0]?.parameterId).toBe("channel_calibrations");
    expect(page.items[0]?.deltas[0]?.before).not.toEqual(page.items[0]?.deltas[0]?.after);
  });

  it("consumes the same read-only inspection and entity-indexed schema", async () => {
    serve(fixtures.inspection);
    const review = await getReview("acceptance-inspection");
    expect(review.experiment_id).toBe("reference_lab.temperature_diagnostic");
    expect(review.latest_result?.error).toBeNull();
    expect(
      measurementEntityAxes(fixtures.entity_analysis)[0]?.members.map((entity) => entity.id),
    ).toEqual(["q0", "q1"]);
  });
});
