"""Resolve explicitly declared wheel modules without importing their code."""

from __future__ import annotations

import json
from importlib.metadata import distribution
from pathlib import Path
from typing import TypedDict, cast

from scopecat.kernel.content_identity import sha256_content_hash, sha256_json_hash
from scopecat.records.author_revision import InstalledAuthorPackage


class _DirectURL(TypedDict, total=False):
    dir_info: dict[str, bool]


def _installed_root(module: str, distribution_name: str) -> Path:
    if not module.isidentifier():
        raise ValueError("installed author module must be a top-level Python name")
    dist = distribution(distribution_name)
    direct = dist.read_text("direct_url.json")
    if direct is not None and cast("_DirectURL", json.loads(direct)).get(
        "dir_info", {}
    ).get("editable"):
        raise ValueError(
            f"installed author package {distribution_name} is editable; build and "
            "install a wheel, or keep editable author code in local source_roots"
        )
    inventory = {str(item) for item in dist.files or ()}
    if f"{module}/__init__.py" in inventory:
        root = Path(str(dist.locate_file(module)))
    elif f"{module}.py" in inventory:
        root = Path(str(dist.locate_file(f"{module}.py")))
    else:
        raise ValueError(
            f"{distribution_name} does not own regular module {module}; "
            "namespace packages and editable installations are not supported"
        )
    if root.is_symlink():
        raise ValueError(f"installed author module must not be a symlink: {module}")
    return root


def installed_module_path(module: str, distribution_name: str, selected: str) -> Path:
    """Resolve only beneath the configured module, before HTTP-selected imports."""
    if not all(part.isidentifier() for part in selected.split(".")):
        raise ValueError("analysis module must be a qualified Python module name")
    if selected != module and not selected.startswith(module + "."):
        raise ValueError("module is outside the configured installed author package")
    root = _installed_root(module, distribution_name)
    if selected == module:
        return root / "__init__.py" if root.is_dir() else root
    relative = Path(*selected.split(".")[1:])
    for path in (root / relative.with_suffix(".py"), root / relative / "__init__.py"):
        if path.is_file() and path.resolve().is_relative_to(root.resolve()):
            return path
    raise ValueError(f"installed author module does not exist: {selected}")


def capture_installed_authors(
    packages: tuple[tuple[str, str], ...],
) -> dict[str, InstalledAuthorPackage]:
    """Hash module bytes and resources, not a wheel archive or installer metadata.

    Generated bytecode is excluded. Dependencies with laboratory-owned code must
    also be declared; third-party dependencies retain the environment contract.
    """
    result: dict[str, InstalledAuthorPackage] = {}
    for module, name in packages:
        root = _installed_root(module, name)
        files: dict[str, str] = {}
        paths: list[Path] = []
        if root.is_file():
            paths.append(root)
        else:
            for directory, directories, filenames in root.walk():
                directories[:] = sorted(
                    item for item in directories if item != "__pycache__"
                )
                if any((directory / item).is_symlink() for item in directories):
                    raise ValueError(
                        f"installed author symlink is unsupported: {module}"
                    )
                paths.extend(directory / item for item in sorted(filenames))
        for path in paths:
            if path.suffix in {".pyc", ".pyo"}:
                continue
            if path.is_symlink():
                raise ValueError(f"installed author symlink is unsupported: {module}")
            files[path.relative_to(root.parent).as_posix()] = sha256_content_hash(
                path.read_bytes()
            )
        result[module] = InstalledAuthorPackage(
            distribution=name,
            version=distribution(name).version,
            content_hash=sha256_json_hash(files),
        )
    return result
